language: node_js
node_js:
  - "8"
  - "6"
  - "4"

services:
  - couchdb

before_script: 
  - cd server
  - npm install

notifications:
  email:
    on_success: never
    on_failure: change